### ISSUE TITLE
error during testing 

### ISSUE THREAD

**Issue by llgzr** [open-mmlab/mmskeleton#428]
Hi,

I'm try to test the ST-GCN network on Kinetics Val dataset from this [link](https://drive.google.com/file/d/103NOL9YYZSW1hLoWmYnv5Fs8mK-Ij7qb/view) loading pre-trained model obtained at this [repository](https://drive.google.com/drive/folders/1IYKoSrjeI3yYJ9bO0_z_eDo92i7ob_aF) but when I test the model with this configuration: 

```
weights: ./models/st_gcn.kinetics.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64
```

I always get this results: 

`[ Fri Aug 13 08:34:14 2021 ] 	mean_loss: 59.962378877209076
[ Fri Aug 13 08:34:14 2021 ] 	Top1: 0.24%
[ Fri Aug 13 08:34:14 2021 ] 	Top5: 1.25%`

The reason I try to test the pre-trained model is that I have to train the model on a new dataset with few samples using transfer learning. 
There are some solutions to this problem or have I to re-train the model on Kinetics-Skeleton dataset? 

Thanks.
